// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func InitializeBroadCast() BroadCast {
	message := NewMessage()
	channel := NewChannel(message)
	ff := NewFF(channel)
	broadCast := NewBroadCast(ff)
	return broadCast
}
